TLS1.1以降のみ有効なサーバーのHTTPS接続に失敗する問題を修正
修正前に発生していた例外 (階層は InnerException の順序):

HttpRequestException: An error occurred while sending the request.
  -> WebException: The underlying connection was closed: An unexpected error occurred on a send.
    -> IOException: Authentication failed because the remote party has closed the transport stream.